# Site settings
title: Dave Anderson
short_title: dvndrsn
author: "Dave Anderson"
header-img: img/home-bg.jpg
email: dave@dvndrsn.com
description: "Blogging about programming, music, data and the third dimension."
baseurl: ""
url: "http://dvndrsn.com"
twitter_username: dvndrsn
github_username: dvndrsn
facebook_username: dvndrsn
linkedin_username: dvndrsn

# plugins
plugins: [jekyll-paginate]

# Build settings
markdown: kramdown
# highlighter: pygments
# permalink: pretty
paginate: 5
exclude:
  - "less"
  - "node_modules"
  - "Gruntfile.js"
  - "package.json"
  - "README.md"
  - "tmp/"

# FTP Settings for Gylnn
ftp_host: "ftp.modernairs.com"
ftp_dir: "/public_html/dvndrsn.com"
ftp_passive: false
