# Site settings
title: dvndrsn
header-img: img/home-bg.jpg
email: dave@dvndrsn.com
description: "Blog for recurse center"
baseurl: ""
url: "http://dvndrsn.com"
twitter_username: dvndrsn
github_username:  dvndrsn
facebook_username:  dvndnrsn

# plugins
gems: [jekyll-paginate]

# Build settings
markdown: kramdown
# highlighter: pygments
# permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# FTP Settings for Gylnn
ftp_host: 'ftp.modernairs.com'
ftp_dir: '/public_html/dvndrsn.com'
ftp_passive: false
